### PR TITLE
Updated to 0.9.3

### PR DESCRIPTION
**Pull request by mkrafzick-softfair**
I hope I am doing this right.

### CODE REVIEW

**Comment by mahsoud** [comment]
Looks identical to what I've done, Ill cancel pull request https://github.com/devblok/chocolatey-nomad/pull/2

**Comment by mkrafzick-softfair** [comment]
Am I reading this right? You made a pull request one minute after me? What are the odds?

**Comment by mahsoud** [comment]
yup

**Review by devblok — APPROVED** [review]
We'll see if this will pass chocolatey auto testing. The reason the package is behind is because it started failing and I had no time at all to fix it.

**Pull request merged**
